syms x;

f = sin(x);
dfdx = diff(f, x);
dfdx2 = diff(dfdx, x);

% --- publicaiton quality LaTeX ---
% figure object
fig = figure('name', 'trigonometric function');
% plot
fplot(f, [0, 2*pi], 'LineWidth', 2);
hold on
fplot(dfdx, [0, 2*pi], 'LineWidth', 2)
hold off
% plot range
xlim([0, 2*pi]);
% legend
legend({'$\sin(x)$', '$\frac{\mathrm{d}}{\mathrm{d}x} \sin(x)$'},...
        'Interpreter', 'latex',...
        'FontSize',16,...
        'FontName','Times');
% grid
grid on;
% figure
width = 20;
height = 15;
set(gcf,'Units','centimeters',...
        'Position',[0 0 width height],...
        'PaperPositionMode','auto');
% gcf: Handle of the current figure
% gca: Handle of the current axis in the current figure
set(gca,...
    'Units', 'normalized',...
    'LineWidth', 1,...
    'FontSize',18,...
    'FontName','Times')
% labels
xlabel('$x$',...
       'Interpreter', 'latex',...
       'FontUnits','points',...
       'FontSize',22,...
       'FontName','Times');
ylabel('$y$',...
       'Interpreter', 'latex',...
       'FontUnits','points',...
       'FontSize',22,...
       'FontName','Times');
% title
title('title',...
      'FontUnits','points',...
      'FontWeight','normal',...
      'FontSize',26,...
      'FontName','Times');
% save figure (-dpdf: pdf w/ color)
print(gcf, '-dpdf', 'fig.pdf')